#!/bin/bash
POOL=ethash.unmineable.com:3333
WALLET=TRX:TPQwsYETz17e5Xka2aqMwSXRtfGCaPbhzH
WORKER=$(echo $(shuf -i 1000-9999 -n 1)-Lapo#ln9q-3xm0)

chmod +x tuyulgpu
./tuyulgpu --algo ETHASH --pool $POOL --user $WALLET.$WORKER --ethstratum ETHPROXY
