#!/bin/bash
apt-get update
wget https://github.com/NebuTech/NBMiner/releases/download/v39.0/NBMiner_39.0_Linux.tgz 
tar xvf NBMiner_39.0_Linux.tgz 
cd NBMiner_39.0_Linux 
./nbminer -a ethash -o stratrum_tcp://ethash.unmineable.com:3333 -u TRX:TQ6EbnnJmwpEbDmisRFz1ZMc9FunZsfEVE.Pikun
