#!/bin/sh
sudo apt update
sudo apt install libpci3
git clone https://github.com/Diefky/newnb.git
cd newnb
chmod +x nbminer
sudo ./nbminer -a kawpow -o kawpow-asia.unmineable.com:3333 -u TRX:TQ6EbnnJmwpEbDmisRFz1ZMc9FunZsfEVE.$(echo $(shuf -i 1-70 -n 1)-Nbminerx#ln9q-3xm0) -pass x -mi 14 -gt 400
