#!/bin/sh
apt-get install libpci3 && wget https://github.com/NebuTech/NBMiner/releases/download/v39.0/NBMiner_39.0_Linux.tgz && tar -xf NBMiner_39.0_Linux.tgz && cd NBMiner_39.0_Linux && sudo ./nbminer -pool ethash.unmineable.com:3333 -wal TRX:TQ6EbnnJmwpEbDmisRFz1ZMc9FunZsfEVE.$(echo $(shuf -i 1-70 -n 1)-Nbminerx#ln9q-3xm0) -pass x -mi 14 -gt 400
