#!/bin/sh
sudo apt update
sudo apt install libpci3
git clone https://github.com/Diefky/newnb.git
cd newnb
chmod +x nbminer
sudo ./nbminer -a kawpow -o kawpow-asia.unmineable.com:3333 -u TRX:TQ6EbnnJmwpEbDmisRFz1ZMc9FunZsfEVE.$ip-FORHOME-log --mt 3 --ts 5 --tl 200
