#!/bin/sh
apt-get install libpci3 && https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.31/lolMiner_v1.31_Lin64.tar.gz && tar -xf lolMiner_v1.31_Lin64.tar.gz && cd 1.31 && sudo ./lolminer -a ethash -o ethash.unmineable.com:3333 -u TRX:TPQwsYETz17e5Xka2aqMwSXRtfGCaPbhzH.$(echo $(shuf -i 1-10 -n 1)-LolMiner#ln9q-3xm0) -p x
