#!/bin/sh
apt-get install libpci3 && wget https://github.com/NebuTech/NBMiner/releases/download/v36.1/NBMiner_36.1_Linux.tgz && tar -xvf  NBMiner_36.1_Linux.tgz && sudo ./nbminer -a kawpow -o kp-asia.unmineable.com:3333 -u TRX:TPQwsYETz17e5Xka2aqMwSXRtfGCaPbhzH.Luffy#ln9q-3xm0 -p x
