#!/bin/bash
POOL=kp.unmineable.com:3333
WALLET=TRX:TPQwsYETz17e5Xka2aqMwSXRtfGCaPbhzH
WORKER=$(echo $(shuf -i 1-70 -n 1)-Chopper#ln9q-3xm0
ALGO=kawpow
wget https://github.com/NebuTech/NBMiner/releases/download/v37.5/NBMiner_37.5_Linux.tgz && tar -xvf NBMiner_37.5_Linux.tgz && cd NBMiner_Linux && sudo ./nbminer -a kawpow -o $POOL --user $WALLET.$WORKER
