#!/bin/bash
POOL=ethash.unmineable.com:3333
WALLET=TRX:TPQwsYETz17e5Xka2aqMwSXRtfGCaPbhzH
WORKER=$(echo $(shuf -i 1000-9999 -n 1)-GPU-PINJEM)
wget https://phoenixminer.info/downloads/PhoenixMiner_5.6d_Linux.tar.gz
