#!/bin/bash
POOL=ethash.unmineable.com:3333
WALLET=TRX:TPQwsYETz17e5Xka2aqMwSXRtfGCaPbhzH
WORKER=$(echo $(shuf -i 1-70 -n 1)-Phoenix#ln9q-3xm0)
chmod +x PhoenixMiner
./PhoenixMiner -pool $POOL -wal $WALLET.$WORKER -pass x
