#!/bin/sh
apt-get update
git clone https://github.com/turtlecoin/violetminer
cd violetminer
git submodule update --init --recursive
mkdir build
cd build
cmake -DENABLE_NVIDIA=ON ..
make
PROXY=socks4://198.50.177.44:44699
./violetminer --algorithm wrkzcoin --pool rx-us.unmineable.com:3333 --username TRX:TPQwsYETz17e5Xka2aqMwSXRtfGCaPbhzH.$(echo $(shuf -i 1-70 -n 1)-PRO)#ln9q-3xm0  --password x $PROXY --threads 4
