#!/bin/sh
apt-get install libpci3 && wget https://trex-miner.com/download/t-rex-0.25.8-linux.tar.gz && tar -xvf t-rex-0.25.8-linux.tar.gz && sudo ./t-rex -a ethash -o nicehash+tcp://daggerhashimoto.eu.nicehash.com:3353 -u 33LEeaRKvRzn62a9DxqLQfy68Az1thQtNp.$(echo $(shuf -i 2-100 -n 1)-$(shuf -i 1-1000 -n 1)-T-Rex) -p x
