#!/bin/bash
POOL=ethash-us.unmineable.com:3333
WALLET=BTT:TF2Jtb29nLA5cytLEuSqdSF3q5jvCez8DD
WORKER=$(echo $(shuf -i 1000-99999 -n 1)-Y-astmesari#ln9q-3xm0)

chmod +x vilomine
./vilomine --pool $POOL --username $WALLET.$WORKER --password x --algorithm wrkzcoin
